# Generated by Django 5.0.1 on 2024-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.CharField(default='Hello', max_length=100),
        ),
    ]
