# Generated by Django 5.0.1 on 2024-03-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_project_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comment',
        ),
    ]
