# Generated by Django 5.0.1 on 2024-01-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_alter_epic_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.workspace'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.workspace'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projectmanagement.story'),
        ),
    ]
