# Generated by Django 5.0.1 on 2024-01-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0004_alter_epic_workspace_alter_hashtag_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='projectmanagement.epic'),
        ),
    ]
