# Generated by Django 5.0.1 on 2024-01-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_alter_bug_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs2epic', to='projectmanagement.epic'),
        ),
        migrations.AlterField(
            model_name='story',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories2epic', to='projectmanagement.epic'),
        ),
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks2epic', to='projectmanagement.epic'),
        ),
    ]
