# Generated by Django 5.0.1 on 2024-01-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_alter_bug_epic_alter_story_epic_alter_task_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='projectmanagement.epic'),
        ),
    ]
