# Generated by Django 5.0.1 on 2024-01-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0007_alter_story_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='projectmanagement.sprint'),
        ),
    ]
