# Generated by Django 5.0.1 on 2024-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0007_bug_state_story_state_subtask_state_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Backlog'), (2, 'Active')], default=1),
        ),
    ]
