# Generated by Django 5.0.1 on 2024-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0008_sprint_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Backlog'), (2, 'Active'), (3, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Backlog'), (2, 'Active'), (3, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Backlog'), (2, 'Active'), (3, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Backlog'), (2, 'Active'), (3, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Backlog'), (2, 'Active'), (3, 'Inactive')], default=1),
        ),
    ]
