# Generated by Django 5.0.1 on 2024-01-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0008_alter_story_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='projectmanagement.epic'),
        ),
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projectmanagement.epic'),
        ),
    ]
