# Generated by Django 5.0.1 on 2024-01-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0009_alter_bug_epic_alter_task_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='projectmanagement.workspace'),
        ),
    ]
