# Generated by Django 5.0.1 on 2024-01-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0011_alter_bug_hashtag_alter_epic_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='projectmanagement.hashtag'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='projectmanagement.hashtag'),
        ),
        migrations.AlterField(
            model_name='story',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='projectmanagement.hashtag'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='projectmanagement.hashtag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='projectmanagement.hashtag'),
        ),
    ]
