# Generated by Django 5.0.1 on 2024-01-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0016_alter_bug_hashtag_alter_epic_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projectmanagement.workspace'),
        ),
    ]
