# Generated by Django 5.0.1 on 2024-01-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0017_alter_sprint_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='projectmanagement.workspace'),
        ),
    ]
