# Generated by Django 5.0.1 on 2024-01-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0018_alter_epic_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='projectmanagement.workspace'),
        ),
    ]
